ChangeLog
src/k2hftsvrinfo.cc
tests/test.sh

n/a
Fixed a bug that k2hftfusesvr does not work for FORMAT and FILE_TIMEFORM in INI type configuration.
And changed test codes for it.

Fixed a bug about FORMAT does not work in k2hftfusesvr

---

ChangeLog
configure.ac
make_valiables.sh
src/k2hftsvrinfo.cc
src/k2hftsvrinfo.h

n/a
- Updated submodule dependency for k2htp_dtor/chmpx/k2hash/fullock
- Added lib_version_for_link option to make_valiables.sh
- Supported trimed contents format keyword

Updated changelog for v1.0.23

---

AUTHORS
README.md
configure.ac

n/a
- Added new member to AUTHORS
- Updated README.md
- Updated k2hash/chmpx/k2htp_dtor dependency

Update dependency on k2hash/chmpx/k2htp_dtor and README/AUTHORS

---

ChangeLog

Updated changelog for v1.0.25

---

ChangeLog
buildutils/control.in
buildutils/k2hftfuse.spec.in
configure.ac

n/a
- Fixed spec file and updated dependency
Added requires keyword in spec file for dependent packages and updated version for dependent packages.

Updated files for release 1.0.28

---

.travis.yml
AUTHORS
ChangeLog
README
README.md
buildutils/Makefile.am
buildutils/control.in
buildutils/debian_build.sh
buildutils/k2hftfuse.spec.in
buildutils/make_rpm_changelog.sh
buildutils/make_variables.sh
buildutils/rpm_build.sh
buildutils/travis_builder.sh
configure.ac
src/k2hftcommon.h
tests/k2hftfuse_test_server.ini
tests/k2hftfuse_test_server.json
tests/k2hftfuse_test_server.yaml
tests/k2hftfuse_test_slave.ini
tests/k2hftfuse_test_slave.json
tests/k2hftfuse_test_slave.yaml
tests/k2hftfuse_test_trans_server.ini
tests/k2hftfuse_test_trans_server.json
tests/k2hftfuse_test_trans_server.yaml
tests/k2hftfusesvr_test_trans_server.ini
tests/k2hftfusesvr_test_trans_server.json
tests/k2hftfusesvr_test_trans_server.yaml
tests/test.sh

n/a
- Support packagecloud.io as AntPickax package repository
- Strictification of spec files
- Stricter debian packages
- Covers the OS and each part dependent on its version in each packaging
- Add rpm dedicated packaging script(local packaging available)
- Obsolete testing using the telnet command
- Changed test script according to docker
- Changed README
- Changed README.md and added some badge

Updated files for release 1.0.29

---

build.md
buildja.md

(If there are Issues related to this PullRequest, please list it.)
Use packagecloud.io. to build the source code.

Use packagecloud.io. to build the source code.

---

build.md
buildja.md

(If there are Issues related to this PullRequest, please list it.)
Fixed wrong urls and styles.

Fixed wrong urls and styles.

---

buildutils/travis_builder.sh
src/k2hftfdcache.cc
src/k2hftfdcache.h
src/k2hftplugin.cc

Relevant Issue (if applicable)
#17
Details
Correspondence omission of #17 was addressed.

Fixed misspelling, and etc

---

README.md
src/k2hftfdcache.cc
src/k2hftfusesvr.cc
src/k2hftplugin.cc
src/k2hftutil.cc

n/a
- Added k2hftfuse overview image to README.md
- Fixed codes for cppcheck 1.87

Fixed codes for cppcheck 1.87

---

ChangeLog

n/a
- Fixed codes for cppcheck 1.87 - #22

Updated files for release 1.0.32

---

.gitignore
buildutils/control.in
buildutils/k2hftfuse.spec.in
configure.ac
src/k2hftinfo.cc
src/k2hftwbuf.h

n/a
- Bug fix
- Add files to .gitignore
- Updating dependent package versions

Fixed bugs and updated version of dependency packages

---

ChangeLog

n/a
- Fixed bugs and updated version of dependency packages - #25

Updated files for release 1.0.33

---

ChangeLog

n/a
Fixed misspellings in ChangeLog

Fixed misspellings in ChangeLog

---

ChangeLog

n/a
- Fixed misspellings in ChangeLog - #27

Updated files for release 1.0.34

---

src/k2hftfusesvr.cc
src/k2hftinfo.cc
src/k2hftwbuf.cc

n/a
Fixed a error by cppcheck 1.90/2.1/2.2

Fixed a error by cppcheck

---

src/k2hftfdcache.cc
src/k2hftfusesvr.cc
src/k2hftinfo.cc
src/k2hftinfo.h
src/k2hftsvrinfo.h
src/k2hftutil.cc
src/k2hftwbuf.h

n/a
Fixed errors reported by cppcheck 2.9.

Fixed errors reported by cppcheck 2.9

---

buildutils/debian_build.sh
tests/test.sh

n/a
Fixed the part where the `grep` command parameter was not appropriate.
And replaced the `which` command with `command -v`.

Updated scripts for adding grep params and replacing which to command

---

buildutils/Makefile.am
docs/Makefile.am
src/k2hftcommon.h
src/k2hftdbg.cc
src/k2hftdbg.h
src/k2hftfdcache.cc
src/k2hftfdcache.h
src/k2hftfuse.cc
src/k2hftfusesvr.cc
src/k2hftinfo.cc
src/k2hftinfo.h
src/k2hftiniparser.cc
src/k2hftiniparser.h
src/k2hftman.cc
src/k2hftman.h
src/k2hftplugin.cc
src/k2hftplugin.h
src/k2hftstructure.h
src/k2hftsvrinfo.cc
src/k2hftsvrinfo.h
src/k2hftutil.cc
src/k2hftutil.h
src/k2hftwbuf.cc
src/k2hftwbuf.h
tests/k2hftfusetest.cc

n/a
Reviewed source code header and footer comments.

Updated header and footer in comment lines

---

.github/workflows/build_helper.sh
.github/workflows/ci.yml
.github/workflows/ostypevars.sh
buildutils/APKBUILD.templ.in
buildutils/alpine_build.sh
buildutils/control.in
buildutils/debian_build.sh
buildutils/k2hftfuse.spec.in
configure.ac
src/k2hftinfo.cc
tests/test.sh

n/a
Supported the ALPINE package.
Added ALPINE to the supported OS and changed other distributions to the latest version.

Changed CI OSs and added Alpine OS

---

.github/workflows/build_helper.sh
buildutils/APKBUILD.templ.in
buildutils/Makefile.am
buildutils/alpine_build.sh
buildutils/control.in
buildutils/debian_build.sh
buildutils/k2hftfuse.spec.in
buildutils/rpm_build.sh
tests/k2hftfusetest.cc
tests/test.sh

n/a
Fixed and updated scripts, packages, dependencies, etc. related to `ALPINE`.
And updated the build helper scripts.

Updated building/packaging logic for ALPINE

---

ChangeLog

n/a
- Updated building/packaging logic for ALPINE - #50

Updated files for release 1.0.38

---

tests/test.sh

n/a
There was a problem in the test script and it has been fixed.

Fixed bugs about test scripts

---

ChangeLog

n/a
- Updated tool scripts and support OSs - #54
- Fixed bugs about test scripts - #53
- Fixed .gitignore to exclude APKBUILD.templ - #52

Updated files for release 1.0.39

---

buildutils/control.in
buildutils/k2hftfuse.spec.in
configure.ac

n/a
By the CHMPX package update, the versions of dependent packages have been updated.

Updated versions of dependent packages

---

ChangeLog

n/a
- Updated versions of dependent packages - #56

Updated files for release 1.0.40

---

ChangeLog

n/a
- Changed support OS (fedora and ubuntu) and updated tool - #58

Updated files for release 1.0.41

---

ChangeLog

n/a
- Updated build_helper.sh for fixing a bug and installing ruby - #60

Updated files for release 1.0.42

---

.github/workflows/ci.yml
.github/workflows/ostypevars.sh
Makefile.am
buildutils/control.in
buildutils/k2hftfuse.spec.in
configure.ac
src/k2hftfuse.cc
src/k2hftfusesvr.cc
src/k2hftinfo.cc
src/k2hftiniparser.cc
src/k2hftman.cc
src/k2hftplugin.cc
src/k2hftstructure.h
src/k2hftsvrinfo.cc
src/k2hftwbuf.cc

n/a
Supported OS has been changed.
- Does not support fedora 37
- Added support for fedora 39
- Added support for Alpine 3.19
Fixed cppcheck errors.
Changed the version of actions/checkout.

Changed support OS and Fixed about cppcheck, etc

---

ChangeLog

n/a
- Changed support OS and Fixed about cppcheck, etc - #62

Updated files for release 1.0.43

---

ChangeLog

n/a
- Changed supported OS and modified some codes - #64

Updated files for release 1.0.44

---

.github/workflows/build_helper.sh
.github/workflows/ci.yml
.github/workflows/ostypevars.sh
AUTHORS
README
README.md
autogen.sh
buildutils/alpine_build.sh
buildutils/debian_build.sh
buildutils/make_commit_hash.sh
buildutils/make_commit_hash_source.sh
buildutils/make_description.sh
buildutils/make_release_version_file.sh
buildutils/make_rpm_changelog.sh
buildutils/make_variables.sh
buildutils/rpm_build.sh
tests/test.sh

n/a
- Ubuntu 20.04 is no longer supported
- ALPINE 3.18 is no longer supported
- ALPINE 3.21 is now supported
- Changed the base of ALPINE's Docker image to ALPINE 3.21
- Fixed minor bugs in some scripts and changed the logic
- Modified the README content and changed the email address

Changed support OSes and Fixed scripts, etc

---

ChangeLog

n/a
- Changed support OSes and Fixed scripts, etc - #67

Updated files for release 1.0.45

---

ChangeLog

n/a
- Avoided latest cppcheck error which maybe a false positive - #69

Updated files for release 1.0.46
